Support parse inner scope function
octoml/synr pull request #2
Opened 2021-06-03 05:04 UTC by wrongtest

Currently, parse a closure function in non-global scope will lead to indentation error.
```python
def some_process():
    def myfunc()
        pass
    sync.to_ast(myfunc, myprinter)
```
This PR try detect closure function by indentation of the first line. Then it wraps the code to make py_ast work normally, and lastly fixes the return structure.

2021-06-03 06:07 UTC, junrushao1994 commented
Thanks for the contribution! I encountered this issue before but didn't have expertise working on synr.

CC: @tkonolige @Hzfengsy @spectrometerHBH

2021-06-07 20:20 UTC, tkonolige commented
Thank you for submitting a PR. However, the correct way to handle this would be to remove leading spaces from the first line of the source program and then remove the same amount of spaces from all subsequent lines. You'd need to add a `start_column` parameter to the `Compiler` class and flow this through to `span_from_ast`.

2021-06-07 20:21 UTC, tkonolige requested changes
Thank you for submitting a PR. However, the correct way to handle this would be to remove leading spaces from the first line of the source program and then remove the same amount of spaces from all subsequent lines. You'd need to add a `start_column` parameter to the `Compiler` class and flow this through to `span_from_ast`.

2021-06-09 03:57 UTC, wrongtest commented
Hi, I re-push the code which works by removing leading spaces as the advice.  Can you kindly take a review on it?  @tkonolige

2021-06-09 16:46 UTC, tkonolige approved these changes
Looks good. Thank you!

2021-06-10 06:59 UTC, Hzfengsy approved these changes
Thanks for the contribution!

2021-06-10 16:10 UTC, merged

2021-06-10 16:10 UTC, tkonolige commented
Thank you @wrongtest!